language: go
sudo: required
services:
 - docker
go:
    - 1.9

install:
    - go get
    - go install github.com/kcmerrill/alfred/

script:
    - docker build -t kcmerrill/alfred .
    - docker run -ti --rm kcmerrill/alfred test
