automagicproxy:
    summary: Start Proxy
    command: >
        docker exec -ti automagicproxy hostname || docker start automagicproxy || 
        docker
        run
        -d
        -p 80:80
        -p 443:443
        -v /var/run/docker.sock:/var/run/docker.sock
        --restart=always
        --name automagicproxy
        kcmerrill/automagicproxy
        --dockerized
        --containerized
        {{ index .Args 0 }}
    defaults:
        - " "

fetch-proxy:
    summary: Start Fetch Proxy
    command: >
        docker exec -ti fetch-proxy hostname || docker start fetch-proxy || 
        docker
        run
        -d
        -p 80:80
        -p 443:443
        -v /var/run/docker.sock:/var/run/docker.sock
        -e DOCKER_API_VERSION=1.24
        --restart=always
        --name fetch-proxy
        kcmerrill/fetch-proxy
        --containerized
        {{ index .Args 0 }}
    defaults:
        - " "

staticwebserver:
    summary: Start a static webserver
    tasks: fetch-proxy
    command: |
        alfred /docker kill.remove ${PWD##*/}
        docker run -d -P -v $PWD:/var/www/html --name ${PWD##*/} kcmerrill/base

webserver:
    summary: Start a webserver(requires html directory)
    tasks: fetch-proxy
    command: |
        alfred /docker kill.remove ${PWD##*/}
        docker run -d -P -v $PWD:/var/www --name ${PWD##*/} kcmerrill/base


phpinfo:
    summary: PHPInfo for kcmerrill/base
    tasks: fetch-proxy
    dir: phpinfo
    command: |
        echo "<?php phpinfo();" > index.php
        alfred /docker kill.remove phpinfo
        docker run -d -P -v $PWD/phpinfo:/var/www/html --name phpinfo kcmerrill/base
        
jenkins:
    summary: Start a jenkins env
    command: |
         docker start jenkins || docker run -d  -v /var/run/docker.sock:/var/run/docker.sock -v $(which docker):$(which docker) --name=jenkins -p 8080:8080 -p 50000:50000 --user root jenkins
