github:
    summary: Install a github repo
    usage: alfred /project setup user/repo
    git: clone {{ index .Args 0 }}
    tasks: setup
    exit: 1

github-revision:
    summary: Install a github repo with a specific revision
    usage: alfred /project setup user/repo commitid
    command: |
        alfred /git clone {{ index .Args 0 }}
    tasks: setup-revision

setup:
    summary: Run alfred install
    command: |
        cd $(ls -td -- */ | head -n 1) && alfred install

setup-revision:
    summary: Checkout a specific revision
    command: |
        cd $(ls -td -- */ | head -n 1)
        alfred /git checkout {{ index .Args 1 }}
        alfred setup
        alfred up
        alfred test
    defaults:
        - master
